#!/bin/zsh

if [[ $murder ]]; then
  # Stop containers.
  docker-compose stop

  # Delete containers.
  docker rm -f $(docker ps -a -q)
  
  # Delete volumes.
  docker volume rm $(docker volume ls -q)

  # Delete images
  docker rmi $(docker images -q)
fi
