#!/bin/zsh

if [[ $murder ]]; then
  # Running containers.
  containers="$(docker ps -a)"
  docker stop $containers
  
  # Stopped containers.
  stoppedContainers="$(docker ps -a -q)"
  docker rm $stoppedContainers

  echo 'All existing containers:'
  docker ls -a

  # Images
  images="$(docker images -q)"
  docker rmi $images

  echo 'All existing images:'
  docker images ls

  # Volumes
  volumes="$(docker volume ls -q)"
  docker volume rm $volumes

  echo 'All existing volumes:'
  docker volume ls
fi
