#!/bin/zsh

if type $drush >/dev/null 2>&1; then
  if [[ $du ]]; then
    cd "$HOME/$projectsDirectory/$du" && "$drush cr" && "$drush updb -y" && "$drush cex -y"

    echo 'Drush executions complete.'
    echo
    echo 'Should I commit? (y/n)'
    read commit

    if [[ $commit == 'y' || $commit == 'yes' ]]; then
      if type $gitclient >/dev/null 2>&1; then
        cd "$HOME/$projectsDirectory/$du" && "$gitclient add ." && "$gitclient commit -m Core update complete."
        echo
        echo 'Core update complete.'
        echo
      else
        echo 'Git not installed or alias not defined in your.launcher.settings.'
        echo
        echo 'Install git, or make sure that $git is defined as your git alias.'
        echo
      fi
    fi
  fi
else
  echo
  echo 'Drush not installed or alias not defined in your.launcher.settings.'
  echo
  echo 'Install drush, or make sure that $drush is defined as your drush alias.'
  echo
fi
