#!/bin/zsh

# Run dashboard command.
# Placed into function as its ran multiple times.
dashboard_check () {
  $terminus -q dashboard $1
}

set_subdirectory () {
  # Magento.
  if [[ -d "$1$2$3/app" ]]; then
    if [[ $noaai == true ]]; then
      app='admin'
    else
      app='manage'
    fi
  fi

  # Drupal.
  if [[ -d "$1$2$3/sites" ]]; then
    app='user'
  fi

  # Wordpress.
  if [[ -d "$1$2$3/wp-content" ]]; then
    app='wp-admin'
  fi
}

# Detect project framework.
# With possible sub-directory modifier.
set_subdirectory "$projects" "$project" "$sub"


# Open project homepage.
open "http://$project$suffix"

# Open project framework management page.
if [[ $app ]]; then
  open "http://$project$suffix/$app"
fi


# Open Pantheon dashboard
if type $terminus >/dev/null 2>&1; then
  dashboard_check "$project"

  # If command failed.
  if [[ $? -eq 1 ]]; then
    if [[ $pantheonPrefix ]]; then
      echo "Trying with '$pantheonPrefix' prefix"
      dashboard_check "$pantheonPrefix$project"

      if [[ $? -eq 0 ]]; then
        echo 'Prefix successful, dashboard opened.'
      else
        echo 'Not found, weird one.'
        echo 'Here, maybe we can find it with our alias search...'
        eval launcher aliases.$project
      fi
    fi

    if [[ $? -eq 1 ]]; then
      echo 'Your project name does not match a sites name in Pantheon.'
      echo
      echo 'What is the name of this project in Pantheon?'
      read pantheonName
      echo
      echo 'Thanks, opening.'
      dashboard_check "$pantheonName"

      if [[ $? -eq 1 ]]; then
        echo 'That still threw an error, check the site name and try again.'
      fi
    fi
  fi    
fi
