#!/bin/bash

# Run dashboard command.
# Placed into function as its ran multiple times.
dashboard_check () {
  $terminus -q dashboard $1
}

# Detect project framework.
# With possible sub-directory modifier.

# Magento.
if [[ -d "$projects$project$sub/app" ]]; then
  if [[ $noaai == true ]]; then
    app='admin'
  else
    app='manage'
  fi
fi

# Drupal.
if [[ -d "$projects$project$sub/sites" ]]; then
  app='user'
fi

# Wordpress.
if [[ -d "$projects$project$sub/wp-content" ]]; then
  app='wp-admin'
fi


# Open project homepage.
open "http://$project.ash"

# Open project framework management page.
if [[ $app ]]; then
  open "http://$project.ash/$app"
fi


# Open Pantheon dashboard
if type $terminus >/dev/null 2>&1; then
  dashboard_check "$project"

  # If command failed.
  if [[ $? -eq 1 ]]; then
    if [[ $pantheonPrefix ]]; then
      echo "Trying with '$pantheonPrefix' prefix"
      dashboard_check "$pantheonPrefix$project"
    fi

    if [[ $? -eq 1 ]]; then
      echo 'Your project name does not match a sites name in Pantheon.'
      echo
      echo 'What is the name of this project in Pantheon?'
      read pantheonName
      echo
      echo 'Thanks, opening.'
      dashboard_check "$pantheonName"

      if [[ $? -eq 1 ]]; then
        echo 'That still threw an error, check the site name and try again.'
      fi
    fi
  fi    
fi
