#!/bin/bash

# Check if homebrew is installed.
# If not, stop the machinations.
if type brew >/dev/null 2>&1; then
  installed=true
else
  echo "Brew is not installed on your system, this won't work"
  echo 'Install homebrew or gtfo. Smiley face.'
  exit 0
fi
