#!/bin/bash

# Kill programs opened by launcher.
# For quickly closing everything opened in order to open new project.
if [[ $kill == true ]]; then
  # Local domain suffix specified in .launcher.settings.
  if [[ $suffix ]]; then
    suffix=".$suffix"



# Close all browser tabs that contain local domain suffix.

# Firefox seems to have limited applescript support, will have to investigate other methods.
# Firefox may be ran via commandline.

# There is an addon called mozrepl/wiki that will allow us to interacti with windows and create our own custom commands.

# We can install an addon from the commandline.
# We should ask to install the addon, install it, then we can use it to close specific tabs.



osascript <<EOD
  set ideapp to "$ideapp"
  set gitapp to "$gitapp"

  tell application ideapp to quit
  tell application gitapp to quit
EOD

  fi
fi

# Broken
# Removed for now until I can figure out a workaround.
# Otherwise crashes the whole script.
#
# set browserapp to "$browserapp"
# tell application browserapp
#   try
#     set windowCount to number of windows
#     repeat with thiswindow from 1 to windowCount
#         set tabCount to number of tabs in window thiswindow
#         set counter to 1
#         repeat tabCount times
#             set thistab to tab counter of window thiswindow
#             set check to URL of thistab
#             if check contains "$suffix" then close thistab
#             set counter to (counter + 1)
#         end repeat
#     end repeat
#   on error
#     display dialog errMsg as text
#   end
# end tell
