#!/bin/zsh

# Check and set parameters and options.
if [[ ! $* ]]; then
  help=true
fi

for item in $*
do
  case $item in
    '7.4' | '8.1' | '8.2' | '8.3' | '8.4' | '8.5')
      phpchange=$item
      ;;
    'terminus.'* | 't.'*)
      terminusValue=${item#*.}
      ;;
    'aliases.'* | 'a.'*)
      aliasValue=${item#*.}
      ;;
    '-y')
      yes=$item
      ;;
    '-h' | '-help' | '--help')
      help=$item
      ;;
    '-p')
      pantheon=true
      ;;
    '-sub='*)
      sub=${item#*=}
      ;;
    '-noaai')
      noaai=true
      ;;
    '-d')
      deploy=true
      ;;
    'kill')
      kill=true
      ;;
    *)
      # Do a '-' check to make sure this isn't an option.
      # If it has a check we should return to use -help.

      # Check for a number or number with decimal.
      check="^[0-9]+([.][0-9]+)?$"
      if [[ $item == -* || $item =~ $check ]]; then
        echo
        echo "Yo, monkeypants, $item is not an option. Do a \"launcher -help\" to see whats powers you may bend towards your nefarious plotting."
        echo
        exit 0
      else
        kill=$kill
      fi
  esac
done
