#!/bin/zsh

# Check and set parameters and options.
if [[ ! $* ]]; then
  help=true
fi

for item in $*
do
  case $item in
    '5.4' | '5.6' | '7.0' | '7.1' | '7.2' | '7.3' | '7.4')
      phpchange=$item
      ;;
    'bloodbath')
      murder=true
      ;;
    'terminus.'* | 't.'*)
      terminusValue=${item#*.}
      ;;
    'local.'* | 'l.'* | 'l.'*'.f')
      # d=database, f=files
      targeted=('d' 'f')

      # Strip localValue prefix an suffix.
      localValue=${item#*.}
      localValue=${localValue%.*}

      # If a targeted run.
      if [[ ${targeted[@]} =~ ${item##*.}  ]]; then
        targetedRun=true
      fi

      # Build local files only.
      if [[ ${item##*.} == 'f' ]]; then
        filesOnly=true
      fi

      # Build local database only.
      if [[ ${item##*.} == 'd' ]]; then
        databaseOnly=true
      fi
      ;;
    'aliases.'* | 'a.'*)
      aliasValue=${item#*.}
      ;;
    'du.'*)
      du=${item#*.}
      ;;
    '-y')
      yes=$item
      ;;
    '-h' | '-help' | '--help')
      help=$item
      ;;
    '-p')
      pantheon=true
      ;;
    '-sub='*)
      sub=${item#*=}
      ;;
    '-noaai')
      noaai=true
      ;;
    '-d')
      deploy=true
      ;;
    'kill')
      kill=true
      ;;
    *)
      # Do a '-' check to make sure this isn't an option.
      # If it has a check we should return to use -help.

      # Check for a number or number with decimal.
      check="^[0-9]+([.][0-9]+)?$"
      if [[ $item == -* || $item =~ $check ]]; then
        echo
        echo "Yo, monkeypants, $item is not an option. Do a \"launcher -help\" to see whats powers you may bend towards your nefarious plotting."
        echo
        exit 0
      else
        project=$item
        kill=$kill
      fi
  esac
done
