#!/bin/zsh

# Mac default php version always the latest version.
# Located at /usr/local/bin/php.

# Homebrew does not contain symlinks for this version.
# Lets add them.

# Check if php symlinks are installed.
# This is done to allow switching to php [version] using the 'php@[version]'.

# Get current php base version.
# Output is always 'php [x.x.x]'.
# Regex to '[x.x]' and remove leading whitespace.
basePhpVersion=$(brew list --versions php | grep -oE --regexp=' ...' | tr -d '[[:space:]]')
basePhpVersionNoDot=${basePhpVersion//.}

php="/opt/homebrew/Cellar/php$basePhpVersionNoDot"
php_path="/opt/homebrew/Cellar/php@$basePhpVersion"

# Checks if symlink exists regardless of if what it points to exists (-L).
# Check if symlink exists and what it points to exists, regardless of type (-e).
# If both do not exist, we create them.
if ! [[ -L $php && -L $php_path ]]; then
  cd /opt/homebrew/Cellar && ln -s php@$basePhpVersion php$basePhpVersionNoDot && ln -s /usr/local/bin/php php@$basePhpVersion 
fi
