#!/bin/zsh

# Capture current php version.
phpversion=$(php -i aux | grep 'PHP Version' | head -1)
set -- $phpversion

# PHPVERSION
# Limit to numbers and periods only.
phpversion=${phpversion//[!0-9.]/}
# Limit to major and minor version numbers only.
phpversion=${phpversion:0:3}

# If: php version passed and they are equal.
# Elif: only run if a change number was passed.
if [[ $phpversion && $phpversion == $phpchange ]]; then
  echo
  echo "HEY!"
  echo "Php current version and specified version are the same, you lunk."
  echo
  php -v
  echo
elif [[ ! -z $phpchange ]]; then
  # Update php version and reload source.
  # Remove any php@ references within .zshrc file.
  awk '!/php@/' $phpExportTarget > temp && mv temp $phpExportTarget

  # Export new php version to path
  echo "export PATH=\"/usr/local/opt/php@$phpchange/bin:/usr/local/opt/php@$phpchange/sbin:\$PATH\"" >> $phpExportTarget

  echo 'Swapping...'

  # Changing php version.
  brew services stop php@$phpversion
  brew unlink php@$phpversion && brew link php@$phpchange --force
  brew services start php@$phpchange

  #Show running console version of php.
  echo
  echo 'Running:'
  echo
  php -v
  echo
fi
