#!/bin/zsh

terminus_loop () {
  # 0 is always dev, on dev never attempt to deploy.
  if [[ $2 == 'dev' ]]; then
    $terminus drush "$site.$2" cr && $terminus -y drush "$site.$2" -- updb -y && $terminus drush "$site.$2" -- cim -y
  else
    $terminus -y env:deploy "$site.$2" && $terminus drush "$site.$2" cr && $terminus drush "$site.$2" -- updb -y && $terminus drush "$site.$2" -- cim -y
  fi
}

# Check that terminus command exists.
if type $terminus >/dev/null 2>&1; then
  if [[ $terminusValue ]]; then
    declare steps=('dev' 'test' 'live')
    site=${terminusValue%.*}
    env=${terminusValue#*.}

    if [[ $site && $env ]]; then
      case $env in
        'dev')
          count=1
          ;;
        'test')
          count=2
          ;;
        'live')
          count=3
          ;;
        'php')
          $terminus env:info $site.live | grep 'PHP Version'
          ;;
        *)
          echo
          echo 'Atempting to run against multidev environment.'
          echo
          echo 'If this was not intended, make sure to specify dev, test or live.'
          echo
          multidev=$env
      esac

      i=1
      if [[ $count ]]; then
        while [[ $i -le $count ]]
        do
          terminus_loop "$i" "${steps[$i]}"
          ((i++))
        done
      else
        terminus_loop "$i" "$multidev"
      fi
    fi
  fi
fi