#!/bin/zsh

is_ok () {
  echo
  echo "$1 (y or n)"
  read response
  echo

  if [[ $response == 'y' || $response == 'yes' ]]; then
    response=true
  else
    response=false
  fi
}

wp_or_drupal() {
  if [[ -d "$1/$localValue/web" ]]; then
    framework=drupal
  fi

  if [[ -f "$1/$localValue/wp-config.php" ]]; then
    framework=wordpress
  fi

  # Set drupal specific variables.
  if [[ $framework == 'drupal' ]]; then
    filesPath='sites/default/files'
  fi

  # Set wordpress specific variables.
  if [[ $framework == 'wordpress' ]]; then
    filesPath='wp-content/uploads'
  fi
}

if_homeovr() {
  # Set default if empty.
  if [[ !$homeovr ]]; then
    homeovr=$HOME
  fi
}

what_project () {
  if [[ $databaseOnly != true && $automate != true ]]; then
    # Strip down to directory name.
    # Accounts for a variety of variance.
    localValue=${terminusValue%.*}
    localValue=${localValue#'aai'}
    localValue=${localValue#'ar-'}
    localValue=${localValue#'mna-'}
    localValue=${localValue%'8'}
    localValue=${localValue%'-8'}
    localValue=${localValue%'-v2'}
    localValue=${localValue%'airport'}
  fi

  if [[ ! -d "$homeovr/$projectsDirectory/$localValue" ]]; then
    echo
    echo 'What project are we building? Name of directory.'
    read directory
    echo
  fi
}

check_brew() {
  installedBrew=false
  
  # Check if homebrew is installed.
  # If not, stop the machinations.
  if type brew >/dev/null 2>&1; then
    installedBrew=true
  else
    echo "Brew is not installed on your system, this won't work"
    echo 'Install homebrew or gtfo. Smiley face.'
    exit 0
  fi
}

check_jq() {
  installedJq=false

  if type jq >/dev/null 2>&1; then
    installedJq=true
  else
    if [[ $installedBrew ]]; then
      is_ok "jq is not installed on your system, mind if I install it with brew?"

      if [[ $response ]]; then
        brew install jq
        installedJq=true
      fi
    else
      check_brew
    fi
  fi
}
