#!/bin/zsh

wp_or_drupal() {
  if [[ -d "$1/$localValue/web" ]]; then
    framework=drupal
  fi

  if [[ -f "$1/$localValue/wp-config.php" ]]; then
    framework=wordpress
  fi

  # Set drupal specific variables.
  if [[ $framework == 'drupal' ]]; then
    filesPath='sites/default/files'
  fi

  # Set wordpress specific variables.
  if [[ $framework == 'wordpress' ]]; then
    filesPath='wp-content/uploads'
  fi
}

if_homeovr() {
  # Set default if empty.
  if [[ !$homeovr ]]; then
    homeovr=$HOME
  fi
}

what_project () {
  # Strip down to directory name.
  # Accounts for a variety of variance.
  localValue=${terminusValue%.*}
  localValue=${localValue#'aai'}
  localValue=${localValue#'mna-'}
  localValue=${localValue%'8'}
  localValue=${localValue%'-v2'}

  if [[ ! -d "$homeovr/$projectsDirectory/$localValue" ]]; then
    echo
    echo 'What project are we building? Name of directory.'
    read directory
    echo
  fi
}
